In [4]:
!pip install pandas numpy sqlalchemy psycopg2-binary -q

In [9]:
import pandas as pd

In [10]:
from pathlib import Path
csv_path = Path(r"C:\Users\user\Desktop\div\data\files\housing.csv")
pd.read_csv(csv_path)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [16]:
username = 'postgres'
password = 'postgres'
database = 'employees'
host = '127.0.0.1'
port = 5432

conn_str = f'postgresql://{username}:{password}@{host}:{port}/{database}'

from sqlalchemy import create_engine
engine = create_engine(conn_str)

In [25]:
query = """
select * 
from employees 
limit 5
"""

df = pd.read_sql_query(query, engine)
df

   emp_no  birth_date first_name last_name gender   hire_date
0   10001  1953-09-02     Georgi   Facello      M  1986-06-26
1   10002  1964-06-02    Bezalel    Simmel      F  1985-11-21
2   10003  1959-12-03      Parto   Bamford      M  1986-08-28
3   10004  1954-05-01  Chirstian   Koblick      M  1986-12-01
4   10005  1955-01-21    Kyoichi  Maliniak      M  1989-09-12

In [24]:
df.iloc[1:3]

   emp_no  birth_date first_name last_name gender   hire_date
1   10002  1964-06-02    Bezalel    Simmel      F  1985-11-21
2   10003  1959-12-03      Parto   Bamford      M  1986-08-28

In [34]:
df2 = pd.DataFrame(
	data=[
		[1,2,3],
		[4,5,6],
		[4,5,6],
		[4,5,6],
	], 
	columns=['a', 'b', 'c']
	)

df2['a'] * 0.1

0    0.1
1    0.4
2    0.4
3    0.4
Name: a, dtype: float64

In [45]:
import numpy as np

a = np.array([1,2,3])
b = np.array([6,7,8])

a*2

array([2, 4, 6])

In [43]:
np.concat([a,b])

array([1, 2, 3, 6, 7, 8])

In [40]:
a = [1,2,3]
b = [6,7,8]

[x+y for x,y in list(zip(a,b))]

[7, 9, 11]

In [46]:
a = [1,2,3]
a*2

[1, 2, 3, 1, 2, 3]

In [71]:
x = np.array([1,2,3], dtype='float')
x.shape

(3,)

In [60]:
type(x)

numpy.ndarray

In [65]:
y = np.array([
	[1,3,3,6],
	[4,5,3,7]
	])

y.shape

(2, 4)

In [ ]:
z = np.array([
	[
		[
			[1,2,3],
			[1,2,3]
		],
		[
			[1,2,3],
			[1,2,3]
		]
	],
	[
		[
			[1,2,3],
			[1,2,3]
		],
		[
			[1,2,3],
			[1,2,3]
		]
	]
])
z.shape

(2, 2, 2, 3)

In [74]:
z.ndim

4

In [75]:
z.size

24