In [3]:
import pandas as pd
import numpy as np

In [ ]:
l = [1,2,3,4]
a = np.array([1,2,3,4])

In [226]:
sheherler = {
	'Baku' : '2,344,900',
	'Sumgait' : '427,000',
	'Ganja' : '330,700',
	'Xırdalan' : '195,700',
	'Mingachevir' : '102,900'	
}

sheherler = {sh:int(e.replace(',', '')) for sh,e in sheherler.items()}
sheher = sheherler.keys()
ehali = sheherler.values()

df = pd.DataFrame({
	'ehali': ehali, 
	'boyukluk' : ['boyuk', 'boyuk', 'boyuk', 'kicik', 'kicik']
},
	index = sheher,
)

df

               ehali boyukluk
Baku         2344900    boyuk
Sumgait       427000    boyuk
Ganja         330700    boyuk
Xırdalan      195700    kicik
Mingachevir   102900    kicik

In [232]:
yeni_ehali = df['ehali'].apply(lambda r: r*1.2)
df.loc[:, 'ehali'] = yeni_ehali
df

               ehali boyukluk
Baku         3376656    boyuk
Sumgait       614880    boyuk
Ganja         476208    boyuk
Xırdalan      281808    kicik
Mingachevir   148176    kicik

In [228]:
df['boyukluk'].mask(df['ehali'] < 5e5, 'orta')

Baku           boyuk
Sumgait         orta
Ganja           orta
Xırdalan        orta
Mingachevir     orta
Name: boyukluk, dtype: str

In [154]:
df.loc['Sumgait':'Ganja','boyukluk'] = 'orta'
df

               ehali boyukluk
Baku         2344900    boyuk
Sumgait       427000     orta
Ganja         330700     orta
Xırdalan      195700    kicik
Mingachevir   102900    kicik

In [105]:
# df.loc[['Baku', 'Ganja'], ['ehali', 'boyukluk']]
# df.iloc[[0,2], [0,1]]
# df['ehali']
mask_e = df['ehali'] < 5e5
mask_b = df['boyukluk'] == 'boyuk'

df2 = df.loc[mask_e & mask_b, :]
df2

          ehali boyukluk
Sumgait  427000    boyuk
Ganja    330700    boyuk

In [111]:
df3 = df2.reset_index()
df3 = df3.rename({'index':'sheher'}, axis='columns')
df3

    sheher   ehali boyukluk
0  Sumgait  427000    boyuk
1    Ganja  330700    boyuk

In [ ]:
# pip install psycopg2-binary

In [135]:
query = """
select * 
from employees 
where 
	first_name = 'Georgi' and last_name is not null;
"""

from sqlalchemy import create_engine
con = create_engine("postgresql+psycopg2://postgres:postgres@localhost:5432/employees")

df = pd.read_sql_query(
	sql=query,
	con=con,
)
df

     emp_no  birth_date first_name  last_name gender   hire_date
0     10001  1953-09-02     Georgi    Facello      M  1986-06-26
1     10909  1954-11-11     Georgi    Atchley      M  1985-04-21
2     11029  1962-07-12     Georgi   Itzfeldt      M  1992-12-27
3     11430  1957-01-23     Georgi    Klassen      M  1996-02-27
4     12157  1960-03-30     Georgi    Barinka      M  1985-06-04
..      ...         ...        ...        ...    ...         ...
248  497046  1959-12-15     Georgi    Rouquie      M  1987-10-15
249  497592  1959-04-22     Georgi     Ariola      M  1986-03-27
250  497609  1956-06-19     Georgi    Rosiles      M  1986-02-24
251  498809  1961-10-24     Georgi   Ferriere      M  1993-02-21
252  499814  1960-12-28     Georgi  Wielonsky      M  1989-01-31

[253 rows x 6 columns]

In [146]:
df.shape

(1000, 5)

In [218]:
df = pd.read_csv(r"C:\Users\user\Desktop\div\data\files\car-sales-extended-missing-data.csv")
# mask = df.loc[:, 'Make'].isna()
# df.loc[mask, 'Make'] = 'Unkown'
df

       Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [223]:
df.isnull().any(axis=1).sum()

np.int64(227)

In [225]:
df.dropna(axis=1, how='all')

       Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [217]:
df.bfill()

       Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996  Nissan  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [215]:
a = df.loc[df['Make'] == 'Honda', 'Odometer (KM)'].mean()
df['Odometer (KM)'].fillna(a)

0       35431.0
1      192714.0
2       84714.0
3      154365.0
4      181577.0
         ...
995     35820.0
996    155144.0
997     66604.0
998    215883.0
999    248360.0
Name: Odometer (KM), Length: 1000, dtype: float64

In [ ]:
a = df['Odometer (KM)'].mean()
df['Odometer (KM)'].fillna(a)

0       35431.0
1      192714.0
2       84714.0
3      154365.0
4      181577.0
         ...
995     35820.0
996    155144.0
997     66604.0
998    215883.0
999    248360.0
Name: Odometer (KM), Length: 1000, dtype: float64

In [ ]:
a = df['Odometer (KM)'].mean()
df['Odometer (KM)'].fillna(a)

0       35431.0
1      192714.0
2       84714.0
3      154365.0
4      181577.0
         ...
995     35820.0
996    155144.0
997     66604.0
998    215883.0
999    248360.0
Name: Odometer (KM), Length: 1000, dtype: float64

In [ ]:
fv = df['Make'].value_counts().idxmax()
df['Make'].fillna(fv)

0       Honda
1         BMW
2       Honda
3      Toyota
4      Nissan
        ...
995    Toyota
996    Toyota
997    Nissan
998     Honda
999    Toyota
Name: Make, Length: 1000, dtype: str

In [189]:
df.notnull()

      Make  Colour  Odometer (KM)  Doors  Price
0     True    True           True   True   True
1     True    True           True   True   True
2     True    True           True   True   True
3     True    True           True   True   True
4     True    True           True   True   True
..     ...     ...            ...    ...    ...
995   True    True           True   True   True
996  False    True           True   True   True
997   True    True           True   True   True
998   True    True           True   True   True
999   True    True           True   True   True

[1000 rows x 5 columns]

In [190]:
df.notnull().sum(axis=0).sum()

np.int64(4751)

In [179]:
mask = df.isnull().any(axis = 1)
df[mask]

       Make Colour  Odometer (KM)  Doors    Price
7     Honda  White            NaN    4.0  20306.0
8       NaN  White       130538.0    4.0   9374.0
13      NaN  White       134181.0    4.0  11121.0
20   Toyota    NaN       124844.0    4.0  24130.0
21    Honda    NaN        30615.0    4.0  29653.0
..      ...    ...            ...    ...      ...
974     NaN  White       155383.0    4.0  14345.0
975   Honda    NaN        22409.0    4.0  10429.0
983  Toyota    Red            NaN    4.0  14671.0
985     NaN   Blue       216250.0    4.0   9691.0
996     NaN  White       155144.0    3.0   5716.0

[227 rows x 5 columns]

In [193]:
df.ffill?

Signature:
df.ffill(
    *,
    axis: 'None | Axis' = None,
    inplace: 'bool' = False,
    limit: 'None | int' = None,
    limit_area: "Literal['inside', 'outside'] | None" = None,
) -> 'Self'
Docstring:
Fill NA/NaN values by propagating the last valid observation to next valid.

Parameters
----------
axis : {0 or 'index'} for Series, {0 or 'index', 1 or 'columns'} for DataFrame
    Axis along which to fill missing values. For `Series`
    this parameter is unused and defaults to 0.
inplace : bool, default False
    If True, fill in-place. Note: this will modify any
    other views on this object (e.g., a no-copy slice for a column in a
    DataFrame).
limit : int, default None
    If method is specified, this is the maximum number of consecutive
    NaN values to forward/backward fill. In other words, if there is
    a gap with more than this number of consecutive NaNs, it will only
    be partially filled. If method is not specified, this is the
    maximum number of entries along the entire axis where NaNs will be
    filled. Must be greater than 0 if not None.
limit_area : {{`None`, 'inside', 'outside'}}, default None
    If limit is specified, consecutive NaNs will be filled with this
    restriction.

    * ``None``: No fill restriction.
    * 'inside': Only fill NaNs surrounded by valid values
      (interpolate).
    * 'outside': Only fill NaNs outside valid values (extrapolate).

    .. versionadded:: 2.2.0

Returns
-------
Series/DataFrame
    Object with missing values filled.

See Also
--------
DataFrame.bfill : Fill NA/NaN values by using the next valid observation
    to fill the gap.

Examples
--------
>>> df = pd.DataFrame(
...     [
...         [np.nan, 2, np.nan, 0],
...         [3, 4, np.nan, 1],
...         [np.nan, np.nan, np.nan, np.nan],
...         [np.nan, 3, np.nan, 4],
...     ],
...     columns=list("ABCD"),
... )
>>> df
     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

>>> df.ffill()
     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  4.0 NaN  1.0
3  3.0  3.0 NaN  4.0

>>> ser = pd.Series([1, np.nan, 2, 3])
>>> ser.ffill()
0   1.0
1   1.0
2   2.0
3   3.0
dtype: float64
File:      c:\users\user\miniconda3\envs\ds\lib\site-packages\pandas\core\generic.py
Type:      method

In [175]:
arr = np.array([
	[True, True],
	[False, False],
	[True, False]
])
arr.all(axis=1)

array([ True, False, False])