In [1]:
from pathlib import Path
import pandas as pd

csv_path = Path(r"C:\Users\user\Desktop\div\data\files\world_population.csv")
# print(csv_path.read_text())

csv_path.exists()

True

In [2]:
df = pd.read_csv(csv_path)
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [3]:
df.tail(3)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [4]:
setirlerin_sayi, sutunlarin_sayi = df.shape
setirlerin_sayi, sutunlarin_sayi

(234, 17)

In [5]:
df.loc[2:10, 'Country':'2022 Population']

                Country           Capital      Continent  2022 Population
2               Algeria           Algiers         Africa       44903225.0
3        American Samoa         Pago Pago        Oceania          44273.0
4               Andorra  Andorra la Vella         Europe          79824.0
5                Angola            Luanda         Africa       35588987.0
6              Anguilla        The Valley  North America          15857.0
7   Antigua and Barbuda      Saint John’s  North America          93763.0
8             Argentina      Buenos Aires  South America       45510318.0
9               Armenia           Yerevan           Asia        2780469.0
10                Aruba        Oranjestad  North America         106445.0

In [6]:
mask = df['Country'] == 'Albania'

df.loc[mask, :]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04

In [7]:
mask = df['Continent'] == 'Europe'

df.loc[mask, :]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
12,99,AUT,Austria,Vienna,Europe,8939617.0,8907777.0,8642421.0,8362829.0,8010428.0,7678729.0,7547561.0,7465301.0,83871.0,106.5877,1.0020,0.11
18,96,BLR,Belarus,Minsk,Europe,9534954.0,9633740.0,9700609.0,9731427.0,10256483.0,10428525.0,9817257.0,9170786.0,207600.0,45.9295,0.9955,0.12
19,81,BEL,Belgium,Brussels,Europe,11655930.0,11561717.0,11248303.0,10877947.0,10264343.0,9959560.0,9828986.0,9629376.0,30528.0,381.8111,1.0038,0.15
25,137,BIH,Bosnia and Herzegovina,Sarajevo,Europe,3233526.0,3318407.0,3524324.0,3811088.0,4179350.0,4494310.0,4199820.0,3815561.0,51209.0,63.1437,0.9886,0.04
30,108,BGR,Bulgaria,Sofia,Europe,6781953.0,6979175.0,7309253.0,7592273.0,8097691.0,8767778.0,8980606.0,8582950.0,110879.0,61.1654,0.9849,0.09
46,130,HRV,Croatia,Zagreb,Europe,4030358.0,4096868.0,4254815.0,4368682.0,4548434.0,4873707.0,4680144.0,4492638.0,56594.0,71.2153,0.9927,0.05
49,158,CYP,Cyprus,Nicosia,Europe,1251488.0,1237537.0,1187280.0,1129686.0,948237.0,788500.0,679327.0,640804.0,9251.0,135.2814,1.0059,0.02
50,88,CZE,Czech Republic,Prague,Europe,10493986.0,10530953.0,10523798.0,10464749.0,10234710.0,10301192.0,10270060.0,9795744.0,78865.0,133.0627,0.9984,0.13
51,115,DNK,Denmark,Copenhagen,Europe,5882261.0,5825641.0,5677796.0,5550849.0,5340655.0,5144623.0,5125392.0,4922963.0,43094.0,136.4984,1.0048,0.07
61,156,EST,Estonia,Tallinn,Europe,1326062.0,1329444.0,1314657.0,1331535.0,1396877.0,1570674.0,1476983.0,1361999.0,45227.0,29.3201,0.9980,0.02
65,209,FRO,Faroe Islands,Tórshavn,Europe,53090.0,52415.0,48816.0,48410.0,45660.0,47479.0,43054.0,38416.0,1393.0,38.1120,1.0038,0.00
67,118,FIN,Finland,Helsinki,Europe,5540745.0,5529468.0,5479461.0,5363271.0,5176209.0,4986545.0,4779418.0,4606621.0,338424.0,16.3722,1.0009,0.07
68,23,FRA,France,Paris,Europe,64626628.0,64480053.0,63809769.0,62444567.0,58665453.0,56412897.0,53713830.0,50523586.0,551695.0,117.1419,1.0015,0.81
74,19,DEU,Germany,Berlin,Europe,83369843.0,83328988.0,82073226.0,81325090.0,81551677.0,79370196.0,77786703.0,78294583.0,357114.0,233.4544,0.9995,1.05
76,219,GIB,Gibraltar,Gibraltar,Europe,32649.0,32709.0,32520.0,31262.0,27741.0,27317.0,28734.0,26685.0,6.0,5441.5000,0.9994,0.00
77,90,GRC,Greece,Athens,Europe,10384971.0,10512232.0,10806641.0,11033783.0,11038109.0,10302255.0,9307148.0,8544873.0,131990.0,78.6800,0.9942,0.13
83,207,GGY,Guernsey,Saint Peter Port,Europe,63301.0,62794.0,61629.0,60782.0,59114.0,57727.0,52860.0,52656.0,78.0,811.5513,1.0037,0.00
90,94,HUN,Hungary,Budapest,Europe,9967308.0,9750573.0,9844246.0,9986825.0,10202055.0,NaN,NaN,10315366.0,93028.0,107.1431,1.0265,0.12
91,179,ISL,Iceland,Reykjavík,Europe,372899.0,366669.0,331060.0,318333.0,281462.0,NaN,NaN,204468.0,103000.0,3.6204,1.0069,0.00
96,125,IRL,Ireland,Dublin,Europe,5023109.0,4946119.0,4665760.0,4524585.0,3768950.0,3485374.0,3391387.0,2937637.0,70273.0,71.4799,1.0073,0.06
97,202,IMN,Isle of Man,Douglas,Europe,84519.0,84046.0,83593.0,83828.0,75562.0,68865.0,64022.0,55298.0,572.0,147.7605,1.0030,0.00
99,25,ITA,Italy,Rome,Europe,59037474.0,59500579.0,60232906.0,59822450.0,56966397.0,56756561.0,56329482.0,53324036.0,301336.0,195.9191,0.9966,0.74
103,195,JEY,Jersey,Saint Helier,Europe,110778.0,108319.0,100561.0,96151.0,86192.0,82874.0,75124.0,68347.0,116.0,954.9828,1.0106,0.00
111,151,LVA,Latvia,Riga,Europe,1850651.0,1897052.0,1991955.0,2101530.0,2392530.0,2689391.0,2572037.0,2397414.0,64559.0,28.6660,0.9876,0.02
116,216,LIE,Liechtenstein,Vaduz,Europe,39327.0,38756.0,37355.0,35926.0,33026.0,28765.0,25003.0,21089.0,160.0,245.7937,1.0074,0.00
117,141,LTU,Lithuania,Vilnius,Europe,2750055.0,2820267.0,2963765.0,3139019.0,3599637.0,3785847.0,3521206.0,3210147.0,65300.0,42.1142,0.9869,0.03
118,168,LUX,Luxembourg,Luxembourg,Europe,647599.0,630399.0,569408.0,507070.0,435628.0,381267.0,363741.0,339342.0,2586.0,250.4250,1.0129,0.01
125,173,MLT,Malta,Valletta,Europe,533286.0,515357.0,456579.0,418755.0,399212.0,365392.0,333587.0,315414.0,316.0,1687.6139,1.0124,0.01
133,135,MDA,Moldova,Chisinau,Europe,3272996.0,3084847.0,3277388.0,3678186.0,4251573.0,4480199.0,4103240.0,3711140.0,33846.0,96.7026,1.0691,0.04
134,217,MCO,Monaco,Monaco,Europe,36469.0,36922.0,36760.0,33178.0,32465.0,30329.0,27076.0,24270.0,2.0,18234.5000,0.9941,0.00
136,169,MNE,Montenegro,Podgorica,Europe,627082.0,629048.0,633966.0,631044.0,633324.0,621442.0,589324.0,530268.0,13812.0,45.4012,0.9988,0.01
144,71,NLD,Netherlands,Amsterdam,Europe,17564014.0,17434557.0,17041107.0,16617116.0,15899135.0,14944548.0,14130387.0,13037686.0,41850.0,419.6897,1.0036,0.22
152,150,MKD,North Macedonia,Skopje,Europe,2093599.0,2111072.0,2107962.0,2093828.0,2037936.0,2044174.0,1907023.0,1656783.0,25713.0,81.4218,0.9954,0.03
154,120,NOR,Norway,Oslo,Europe,NaN,5379839.0,NaN,4889741.0,4491202.0,4241636.0,4085776.0,3875546.0,323802.0,16.7828,1.0058,0.07
164,37,POL,Poland,Warsaw,Europe,39857145.0,38428366.0,38553146.0,38597353.0,38504431.0,38064255.0,35521429.0,32482943.0,312679.0,127.4698,1.0404,0.50
165,92,PRT,Portugal,Lisbon,Europe,10270865.0,10298192.0,10365435.0,10588401.0,10300626.0,10007346.0,9785252.0,8683631.0,92090.0,111.5307,0.9981,0.13
170,64,ROU,Romania,Bucharest,Europe,19659267.0,19442038.0,19906079.0,20335211.0,21919876.0,22836234.0,22125224.0,19922618.0,238391.0,82.4665,1.0171,0.25
171,9,RUS,Russia,Moscow,Europe,144713314.0,145617329.0,144668389.0,143242599.0,146844839.0,148005704.0,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81
180,218,SMR,San Marino,San Marino,Europe,33660.0,34007.0,33570.0,31608.0,NaN,23132.0,21346.0,18169.0,61.0,551.8033,0.9975,0.00
184,105,SRB,Serbia,Belgrade,Europe,7221365.0,7358005.0,7519496.0,7653748.0,7935022.0,7987529.0,7777010.0,7193533.0,88361.0,81.7257,0.9897,0.09
189,116,SVK,Slovakia,Bratislava,Europe,5643453.0,5456681.0,5424444.0,5396424.0,5376690.0,5261305.0,4973883.0,4522867.0,49037.0,115.0856,1.0359,0.07
190,148,SVN,Slovenia,Ljubljana,Europe,2119844.0,2117641.0,2080862.0,2057286.0,1984339.0,1986024.0,1901570.0,1741286.0,20273.0,104.5649,1.0002,0.03
196,30,ESP,Spain,Madrid,Europe,47558630.0,47363807.0,46431342.0,46572772.0,40741651.0,38889889.0,37491666.0,33792617.0,505992.0,93.9909,1.0015,0.60
200,87,SWE,Sweden,Stockholm,Europe,10549347.0,10368969.0,9849349.0,9381729.0,8871043.0,8548406.0,8311763.0,8027702.0,450295.0,23.4276,1.0079,0.13
201,101,CHE,Switzerland,Bern,Europe,8740472.0,8638613.0,8281732.0,7822435.0,7182059.0,6711693.0,6319113.0,6181227.0,41284.0,211.7157,1.0056,0.11
218,38,UKR,Ukraine,Kiev,Europe,39701739.0,43909666.0,44982564.0,45683020.0,48879755.0,51589817.0,49973920.0,47279086.0,603500.0,65.7858,0.9120,0.50
220,21,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85
226,234,VAT,Vatican City,Vatican City,Europe,510.0,520.0,564.0,596.0,651.0,700.0,733.0,752.0,1.0,510.0000,0.9980,0.00

In [8]:
mask = df['Continent'] == 'Europe'

df.loc[~mask, :]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
5,42,AGO,Angola,Luanda,Africa,35588987.0,33428485.0,28127721.0,23364185.0,16394062.0,11828638.0,8330047.0,6029700.0,1246700.0,28.5466,1.0315,0.45
6,224,AIA,Anguilla,The Valley,North America,15857.0,15585.0,14525.0,13172.0,11047.0,8316.0,6560.0,6283.0,91.0,174.2527,1.0066,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [9]:
df['2022 Population']/ 1_000_000

0      41.128771
1       2.842321
2      44.903225
3       0.044273
4       0.079824
         ...
229     0.011572
230     0.575986
231    33.696614
232    20.017675
233    16.320537
Name: 2022 Population, Length: 234, dtype: float64

In [10]:
col = 'World Population Percentage'

'population' in col.lower()

True

In [11]:
import re

def pop_sutunlarini_tap(text):
	pattern = "\d{4} Population"
	# text = "World Population Percentage"

	match = re.search(pattern, text)
	return match is not None

pop_sutunlarini_tap("World Population Percentage")

False

In [12]:
cols_to_show = ['Country'] + [col for col in list(df.columns) if pop_sutunlarini_tap(col)]
cols_to_show

['Country',
 '2022 Population',
 '2020 Population',
 '2015 Population',
 '2010 Population',
 '2000 Population',
 '1990 Population',
 '1980 Population',
 '1970 Population']

In [13]:
mask_pop = df['2022 Population'] > 1_000_000

mask_eur = df['Continent'] == 'Europe'

# df.loc[mask_pop, :]
df.loc[mask_pop & mask_eur, cols_to_show]

,Country,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population
1,Albania,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0
12,Austria,8939617.0,8907777.0,8642421.0,8362829.0,8010428.0,7678729.0,7547561.0,7465301.0
18,Belarus,9534954.0,9633740.0,9700609.0,9731427.0,10256483.0,10428525.0,9817257.0,9170786.0
19,Belgium,11655930.0,11561717.0,11248303.0,10877947.0,10264343.0,9959560.0,9828986.0,9629376.0
25,Bosnia and Herzegovina,3233526.0,3318407.0,3524324.0,3811088.0,4179350.0,4494310.0,4199820.0,3815561.0
30,Bulgaria,6781953.0,6979175.0,7309253.0,7592273.0,8097691.0,8767778.0,8980606.0,8582950.0
46,Croatia,4030358.0,4096868.0,4254815.0,4368682.0,4548434.0,4873707.0,4680144.0,4492638.0
49,Cyprus,1251488.0,1237537.0,1187280.0,1129686.0,948237.0,788500.0,679327.0,640804.0
50,Czech Republic,10493986.0,10530953.0,10523798.0,10464749.0,10234710.0,10301192.0,10270060.0,9795744.0
51,Denmark,5882261.0,5825641.0,5677796.0,5550849.0,5340655.0,5144623.0,5125392.0,4922963.0
61,Estonia,1326062.0,1329444.0,1314657.0,1331535.0,1396877.0,1570674.0,1476983.0,1361999.0
67,Finland,5540745.0,5529468.0,5479461.0,5363271.0,5176209.0,4986545.0,4779418.0,4606621.0
68,France,64626628.0,64480053.0,63809769.0,62444567.0,58665453.0,56412897.0,53713830.0,50523586.0
74,Germany,83369843.0,83328988.0,82073226.0,81325090.0,81551677.0,79370196.0,77786703.0,78294583.0
77,Greece,10384971.0,10512232.0,10806641.0,11033783.0,11038109.0,10302255.0,9307148.0,8544873.0
90,Hungary,9967308.0,9750573.0,9844246.0,9986825.0,10202055.0,NaN,NaN,10315366.0
96,Ireland,5023109.0,4946119.0,4665760.0,4524585.0,3768950.0,3485374.0,3391387.0,2937637.0
99,Italy,59037474.0,59500579.0,60232906.0,59822450.0,56966397.0,56756561.0,56329482.0,53324036.0
111,Latvia,1850651.0,1897052.0,1991955.0,2101530.0,2392530.0,2689391.0,2572037.0,2397414.0
117,Lithuania,2750055.0,2820267.0,2963765.0,3139019.0,3599637.0,3785847.0,3521206.0,3210147.0
133,Moldova,3272996.0,3084847.0,3277388.0,3678186.0,4251573.0,4480199.0,4103240.0,3711140.0
144,Netherlands,17564014.0,17434557.0,17041107.0,16617116.0,15899135.0,14944548.0,14130387.0,13037686.0
152,North Macedonia,2093599.0,2111072.0,2107962.0,2093828.0,2037936.0,2044174.0,1907023.0,1656783.0
164,Poland,39857145.0,38428366.0,38553146.0,38597353.0,38504431.0,38064255.0,35521429.0,32482943.0
165,Portugal,10270865.0,10298192.0,10365435.0,10588401.0,10300626.0,10007346.0,9785252.0,8683631.0
170,Romania,19659267.0,19442038.0,19906079.0,20335211.0,21919876.0,22836234.0,22125224.0,19922618.0
171,Russia,144713314.0,145617329.0,144668389.0,143242599.0,146844839.0,148005704.0,138257420.0,130093010.0
184,Serbia,7221365.0,7358005.0,7519496.0,7653748.0,7935022.0,7987529.0,7777010.0,7193533.0
189,Slovakia,5643453.0,5456681.0,5424444.0,5396424.0,5376690.0,5261305.0,4973883.0,4522867.0
190,Slovenia,2119844.0,2117641.0,2080862.0,2057286.0,1984339.0,1986024.0,1901570.0,1741286.0
196,Spain,47558630.0,47363807.0,46431342.0,46572772.0,40741651.0,38889889.0,37491666.0,33792617.0
200,Sweden,10549347.0,10368969.0,9849349.0,9381729.0,8871043.0,8548406.0,8311763.0,8027702.0
201,Switzerland,8740472.0,8638613.0,8281732.0,7822435.0,7182059.0,6711693.0,6319113.0,6181227.0
218,Ukraine,39701739.0,43909666.0,44982564.0,45683020.0,48879755.0,51589817.0,49973920.0,47279086.0
220,United Kingdom,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0

In [14]:
type(df['Country'])

pandas.Series

In [15]:
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [26]:
adlar_listi = ['ali','hesen','lale']
yashlar_listi = [5, 10, 25]

adlar = pd.Series(adlar_listi)
yashlar = pd.Series(yashlar_listi)

df2 = pd.DataFrame(
	data = {
		'ad' : adlar, 
		'yash' : yashlar
	}
)
mask = df2['ad'] == 'hesen'
df2.loc[mask, :]

      ad  yash
1  hesen    10

In [34]:
magaza = {
	"kartof" : 0.8,
	"sogan" : 1.4,
	"alma" : 1.5,
	"banan" : 3
}

magaza.keys(), magaza.values()

(dict_keys(['kartof', 'sogan', 'alma', 'banan']),
 dict_values([0.8, 1.4, 1.5, 3]))

In [62]:
mehsullar = pd.Series(magaza.keys())
qiymetler = pd.Series(magaza.values())

df_magaza = pd.DataFrame(data={
	'mehsul' : mehsullar,
	'qiymet' : qiymetler,
})
mask_kartof = df_magaza['mehsul'] == 'kartof'
mask_sogan = df_magaza['mehsul'] == 'sogan'

odenis = df_magaza.loc[mask_kartof | mask_sogan, 'qiymet'] * 3
odenis.sum()

np.float64(6.6)

In [52]:
csv_path = Path(r"C:\Users\user\Desktop\div\data\files\car-sales-extended-missing-data.csv")
df_cars = pd.read_csv(csv_path)

df_cars.head(3)

    Make Colour  Odometer (KM)  Doors    Price
0  Honda  White        35431.0    4.0  15323.0
1    BMW   Blue       192714.0    5.0  19943.0
2  Honda  White        84714.0    4.0  28343.0

In [61]:
hondalar_maskasi = df_cars['Make'] == 'Honda'
rengler_maskasi = df_cars['Colour'] == 'White'
km_maskasi = df_cars['Odometer (KM)'] >= 50_000
qiymet_maskasi = df_cars['Price'] < 5_000

df_filterlenmis = df_cars.loc[
	hondalar_maskasi & rengler_maskasi & km_maskasi & qiymet_maskasi, :
]

df_filterlenmis['Price'].mean()

np.float64(4021.75)